---
deployment:
  tasks:
    - /bin/echo "=== Deploying vendor-frontend ==="

    - /bin/npm install
    - /bin/npm run build

    - /bin/mkdir -p /home/fuma/public_html/fumavendor

    - /bin/rsync -av --delete build/ /home/fuma/public_html/fumavendor/

    - /bin/echo "=== vendor-frontend deploy complete ==="
