---
deployment:
  tasks:
    - /bin/echo "Starting deployment for vendor-frontend"

    # Install dependencies
    - /usr/local/bin/npm install

    # Build
    - /usr/local/bin/npm run build || { echo "React build failed"; exit 1; }

    # Deployment path
    - export DEPLOYPATH=/home/USERNAME/public_html/fumavendor/

    - /bin/mkdir -p $DEPLOYPATH

    # Copy compiled frontend
    - /bin/rsync -av --delete build/ $DEPLOYPATH

    - /bin/echo "Deployment finished for vendor-frontend"
